const taskListContentHolder = document.createElement('div');
const taskListEditor = document.createElement('div');
const taskInputList = document.createElement('ul');
const taskFormLineContainer = document.createElement('li');
const taskForm = document.createElement('form');
const taskEditorArea = document.createElement('div');
const taskEditorInputContainer = document.createElement('div');
const taskContent = document.createElement('div');
const textHolder = document.createElement('div');
const textEditor = document.createElement('div');
const textEditorPlaceholder = document.createElement('div');
const textPlaceholder = document.createElement('div');
const draftEditor = document.createElement('div');
const textBox = document.createElement('div');
const textBoxDataContent = document.createElement('div');
const taskDescriptionInput = document.createElement('textarea');

// set class
taskListContentHolder.classList = 'task_list_box';
taskListEditor.classList = 'task_list_editor';
taskInputList.classList = 'task_input_list';
taskFormLineContainer.classList = 'task_manager';
taskForm.classList = 'task_form';
taskEditorArea.classList = 'task_editor_area';
taskEditorInputContainer.classList = 'task_input_container';
taskContent.classList = 'task_content';
textHolder.classList = 'text_input';
textEditor.classList = 'draft';
textEditorPlaceholder.classList = 'draft_edit';
textPlaceholder.classList = 'task_placeholder';
draftEditor.classList = 'draft_editor_container';
textBox.classList = 'content';
taskDescriptionInput.classList = 'task_description';

// set attributes
taskListContentHolder.setAttribute('tabindex', '-1');
taskForm.setAttribute('id', 'task_form');
textPlaceholder.setAttribute('placeholder', 'e.g., Lane swimming at 7am');
textPlaceholder.setAttribute('id', 'task_placeholder');
textBox.setAttribute('contenteditable', 'true');
textBox.setAttribute('rol', 'textbox');
textBox.setAttribute('spellcheck', 'true');
textBoxDataContent.setAttribute('data-contents', 'true');
taskDescriptionInput.setAttribute('placeholder', 'Description');
// append
projectEditor.appendChild(taskListContentHolder);
taskListContentHolder.appendChild(taskListEditor);
taskListEditor.appendChild(taskInputList);
taskInputList.appendChild(taskFormLineContainer);
taskFormLineContainer.appendChild(taskForm);
taskForm.appendChild(taskEditorArea);
taskEditorArea.appendChild(taskEditorInputContainer);
taskEditorInputContainer.appendChild(taskContent);
taskContent.appendChild(textHolder);
textHolder.appendChild(textEditor);
textEditorPlaceholder.appendChild(textPlaceholder);
textEditor.appendChild(textEditorPlaceholder);
textHolder.appendChild(draftEditor);
draftEditor.appendChild(textBox);
textBox.appendChild(textBoxDataContent);
taskEditorInputContainer.appendChild(taskDescriptionInput);
